cache:
    directories:
        - $HOME/.stack

env:
    - ENKI_PATH=$TRAVIS_BUILD_DIR/libraries/base

before_install:
    - sudo apt-add-repository -y ppa:swi-prolog/stable
    - sudo apt update
    - sudo apt install -y maude swi-prolog
    - curl -sSL https://get.haskellstack.org/ | sh
    - stack upgrade
    - stack setup
    - stack update
    - ./setup

script:
    # Need to install first, because the later tests for the compiler need the parser
    - cd Parser
    - stack --no-terminal --install-ghc test --only-dependencies
    - stack --no-terminal test
    - stack install
    - cd ..
    - make test

